const OFFERS = [
{id:1,title:"Brand Content & Editorial Manager",company:"French Bloom (LVMH)",contract:"CDI",location:"Paris 8e",salary:"35K - 50K",experience:"3-5 ans",score:98,urgency:"haute",sector:"Luxe / Vins Premium",url:"https://www.welcometothejungle.com/fr/companies/french-bloom/jobs/responsable-e-commerce-univers-luxe-b2c_paris_FB_ZyAMLjw",match:["Univers premium/luxe investi par LVMH - pile dans les secteurs de Marie","Pilotage video A-Z : shootings, tournages, post-prod, reels, TikTok","Direction editoriale & calendrier editorial - parallele avec La Room","Anglais courant exige - C2 de Marie est un atout majeur","Outils IA generative (Midjourney) - Marie les maitrise deja"],tags:["Luxe","Brand Content","Social Media","Video","IA"]},
{id:2,title:"Cheffe de Projet Production",company:"Groupe Rocher (Yves Rocher)",contract:"CDI",location:"Issy-les-Moulineaux (92)",salary:"NC",experience:"3 ans min.",score:95,urgency:"haute",sector:"Beaute / Cosmetiques",url:"https://fr.fashionjobs.com/emploi/yves-rocher/Cdi-chef-fe-de-projet-production-h-f-x,11841213.html",match:["Bras droit Head of Content Production - poste jumeau Peech","Pilotage 360 (photo, video, 3D, IA) pour marques internationales","Gestion complete pre-prod vers post-prod, budgets et delais","Secteur beaute - clients L'Oreal, Chanel deja geres chez Peech","Curiosite IA/3D - maitrise de Marie est un differenciant"],tags:["Beaute","Production","Video","360","IA"]},
{id:3,title:"Brand Content & Editorial Manager",company:"Maison Premium (via Altaide)",contract:"CDI",location:"Paris",salary:"47K - 49K",experience:"3-5 ans",score:93,urgency:"moyenne",sector:"Luxe / Premium",url:"https://www.altaide.com/offre-emploi/brand-content-social-media-manager-h-f/",match:["Maison premium soutenue par grand groupe luxe international","Pilotage strategie editoriale et production creative","Production interne : reels, TikTok, stories, carrousels, videos","Supervision post-production et tournages","Outils IA generative pour ideation et prototypage creatif"],tags:["Luxe","Brand Content","Editorial","Video","IA"]},
{id:4,title:"Chef de Projet Image",company:"Richemont (Van Cleef & Arpels, Cartier)",contract:"CDI",location:"Paris",salary:"NC",experience:"3-5 ans",score:90,urgency:"moyenne",sector:"Luxe / Joaillerie",url:"https://fr.trabajo.org/offre-2958-647fae7d7dd633d18198a77dfeedc102",match:["Groupe Richemont = Van Cleef, Cartier - Marie a travaille sur Van Cleef chez Peech","Post-production photo & video : campagnes, lookbooks, contenus defiles","Coordination shootings, tournages, brief creatif vers livraison finale","Francais & anglais courant requis - C2 de Marie","Sensibilite artistique & rigueur - experience theatre et Peech"],tags:["Haute Joaillerie","Image","Post-prod","Luxe"]},
{id:5,title:"Content & Communication Manager",company:"Spliit",contract:"CDI",location:"Paris 9e",salary:"NC",experience:"3 ans min.",score:87,urgency:"haute",sector:"Tech / Services",url:"https://www.welcometothejungle.com/fr/companies/spliit/jobs/content-communication-manager_paris",match:["Calendrier editorial et production contenus multi-canaux","Social media, newsletters, SEO, video, evenements","Maitrise Canva, Adobe, CapCut exigee - Marie a tout ca","Debut 13 septembre 2026 - poste tres recent","Role central dans la visibilite et notoriete de la marque"],tags:["Tech","Content","Social Media","Video","Communication"]},
{id:6,title:"Chef de Projet Communication",company:"GERESO",contract:"CDI",location:"Paris 14e",salary:"35K - 40K",experience:"4-5 ans",score:82,urgency:"haute",sector:"Formation / B2B",url:"https://candidat.francetravail.fr/offres/recherche/detail/213TZMH",match:["Production contenus audiovisuels et editoriaux","Gestion de projets et coordination prestataires","Reseaux sociaux et community management LinkedIn","Actualisee le 14 septembre 2026 - tres recente","Organisation evenements physiques et digitaux"],tags:["Communication","B2B","Editorial","Social Media","Evenementiel"]},
{id:7,title:"Chef de Projet Livestream",company:"Genysia / Mogador Productions",contract:"CDI",location:"Paris 9e",salary:"NC",experience:"2-5 ans",score:85,urgency:"moyenne",sector:"Production Audiovisuelle",url:"https://www.genysia.com/offres-emploi/chef-de-projet-livesteam",match:["Pilotage prestations audiovisuelles en direct","Cadrage client, configuration technique, planification","Habillage graphique : conducteurs, synthes, visuels, transitions","Studio en interne, regie mobile, parc materiel moderne","Permis B apprecie - Marie l'a"],tags:["Audiovisuel","Livestream","Production","Evenementiel","Technique"]},
{id:8,title:"Social Media & Content Project Manager",company:"Sisley",contract:"CDI",location:"Paris 8e",salary:"36K - 64K",experience:"1-7 ans",score:86,urgency:"moyenne",sector:"Cosmetique Haut de Gamme",url:"https://www.hellowork.com/fr-fr/emplois/79969747.html",match:["Direction Communication Globale de Sisley - cosmetique haut de gamme","Pilotage TikTok, YouTube, Instagram avec strategie annuelle","Creation et montage video exiges - coeur d'expertise Marie","Coordination inter-equipes creatifs/marketing/com"],tags:["Cosmetique","Social Media","Video","Montage","Strategie"]}
];
