const OFFERS = [
{id:1,title:"Brand Content & Editorial Manager",company:"French Bloom (LVMH)",contract:"CDI",location:"Paris 8e",salary:"35K - 50K",experience:"3-5 ans",score:98,urgency:"haute",sector:"Luxe / Vins Premium",url:"https://www.welcometothejungle.com/fr/companies/french-bloom/jobs/responsable-e-commerce-univers-luxe-b2c_paris_FB_ZyAMLjw",match:["Univers premium/luxe investi par LVMH","Pilotage video A-Z : shootings, tournages, post-prod, reels, TikTok","Direction editoriale & calendrier editorial - parallele avec La Room","Anglais courant exige - C2 de Marie est un atout majeur","Outils IA generative (Midjourney) - Marie les maitrise deja"],tags:["Luxe","Brand Content","Social Media","Video","IA"]},
{id:2,title:"Cheffe de Projet Production",company:"Groupe Rocher (Yves Rocher)",contract:"CDI",location:"Issy-les-Moulineaux (92)",salary:"NC",experience:"3 ans min.",score:95,urgency:"haute",sector:"Beaute / Cosmetiques",url:"https://fr.fashionjobs.com/emploi/yves-rocher/Cdi-chef-fe-de-projet-production-h-f-x,11841213.html",match:["Bras droit Head of Content Production - poste jumeau Peech","Pilotage 360 (photo, video, 3D, IA) pour marques internationales","Gestion complete pre-prod vers post-prod, budgets et delais","Secteur beaute - clients L'Oreal, Chanel deja geres chez Peech","Curiosite IA/3D - maitrise de Marie est un differenciant"],tags:["Beaute","Production","Video","360","IA"]},
{id:3,title:"Chef de Projet Image",company:"Richemont (Van Cleef & Arpels, Cartier)",contract:"CDI",location:"Paris",salary:"NC",experience:"3-5 ans",score:90,urgency:"moyenne",sector:"Luxe / Joaillerie",url:"https://fr.trabajo.org/offre-2958-647fae7d7dd633d18198a77dfeedc102",match:["Groupe Richemont = Van Cleef, Cartier - Marie a deja travaille sur Van Cleef chez Peech","Post-production photo & video : campagnes, lookbooks, contenus defiles","Coordination shootings, tournages, brief creatif vers livraison finale","Francais & anglais courant requis - C2 de Marie","Sensibilite artistique & rigueur - experience theatre et Peech"],tags:["Haute Joaillerie","Image","Post-prod","Luxe"]},
{id:4,title:"Chef de Projet Social Media",company:"Printemps",contract:"CDI",location:"Paris",salary:"35K - 45K",experience:"Confirme",score:87,urgency:"haute",sector:"Mode / Retail Luxe",url:"https://fr.trabajo.org/offre-2958-d854d86c2e9838bb4a9c65737ed2775b",match:["Secteur luxe & mode - Printemps acteur emblematique","Animation communaute & creation contenu : UGC, lives, challenges","Formats maitrises par Marie (YouTube/Twitch avec La Room)","Veille tendances social media : IA, formats emergents"],tags:["Mode","Luxe","Social Media","Communaute","UGC"]},
{id:5,title:"Social Media & Content Project Manager",company:"Sisley",contract:"CDI",location:"Paris 8e",salary:"36K - 64K",experience:"1-7 ans",score:85,urgency:"moyenne",sector:"Cosmetique Haut de Gamme",url:"https://www.hellowork.com/fr-fr/emplois/79969747.html",match:["Direction Communication Globale de Sisley - cosmetique haut de gamme","Pilotage TikTok, YouTube, Instagram avec strategie annuelle","Creation et montage video exiges - coeur d'expertise Marie","Coordination inter-equipes creatifs/marketing/com"],tags:["Cosmetique","Social Media","Video","Montage","Strategie"]},
{id:6,title:"Chef de Projet International 360",company:"Dentsu Creative",contract:"CDI",location:"Paris 17e",salary:"NC",experience:"3 ans min.",score:88,urgency:"moyenne",sector:"Agence Creative",url:"https://job.jai-un-pote-dans-la.com/poste/chef-de-projet-international-h-f/",match:["Agence creative internationale - campagnes print, digital, video, social","Coordination multi-marches et parties prenantes","Anglais courant indispensable - C2 de Marie","Experience marques pub + digital + reseaux sociaux","Teletravail flexible - 94% collaborateurs satisfaits"],tags:["Agence","International","360","Digital","Video"]},
{id:7,title:"Content & Social Creative Beaute",company:"Marque beaute (via Approach People)",contract:"CDI",location:"Paris",salary:"NC",experience:"Significative",score:86,urgency:"moyenne",sector:"Beaute / Lifestyle",url:"https://www.jobintree.com/emplois/81360018.html",match:["Strategie creative contenu pour reseaux sociaux","Formats innovants : videos courtes, storytelling, influence, shootings","Pilotage production contenus internes et externes","Sensibilite esthetique et univers beaute"],tags:["Beaute","Social Media","Creative","Shootings","Influence"]},
{id:8,title:"Brand Content & Editorial Manager",company:"Maison Premium (via Altaide)",contract:"CDI",location:"Paris",salary:"47K - 49K",experience:"3-5 ans",score:92,urgency:"moyenne",sector:"Luxe / Premium",url:"https://www.jobintree.com/emplois/81991857.html",match:["Maison premium soutenue par grand groupe luxe international","Pilotage strategie editoriale et production creative","Production interne : reels, TikTok, stories, carrousels, videos","Supervision post-production et tournages","Outils IA generative pour ideation et prototypage creatif"],tags:["Luxe","Brand Content","Editorial","Video","IA"]}
];
