const OFFERS = [
{id:1,title:"Creative Video Producer",company:"Manucurist",contract:"CDI",location:"Paris",salary:"NC",experience:"2-5 ans",score:96,urgency:"haute",sector:"Beaute / Cosmetiques Green",url:"https://fr.trabajo.org/offre-2958-5a9819053a73318478607c67eb89e212",match:["Production video de A a Z pour campagnes et social media - coeur de metier Marie","Collaboration directe avec la Directrice Brand et l'equipe creative","Maitrise CapCut, Premiere Pro, Final Cut, After Effects exigee - Marie les a tous","Secteur beaute premium - clients similaires a ceux de Peech Studio","Declinaison sur tous canaux : e-com, paid ads, retail, reseaux sociaux"],tags:["Beaute","Video","Production","Brand Content","Social Media"]},
{id:2,title:"Content & Social Creative Beaute",company:"Marque Beaute Premium (via Approach People)",contract:"CDI",location:"Paris",salary:"NC",experience:"3-5 ans",score:94,urgency:"haute",sector:"Beaute / Luxe",url:"https://www.jobintree.com/emplois/81360018.html",match:["Strategie creative de contenu pour Instagram, TikTok, YouTube, Pinterest","Concepts creatifs, campagnes sociales et activations digitales","Pilotage production : photographes, videastes, createurs, agences","Moodboards, directions artistiques, recommandations creatives","Secteurs beaute, luxe, mode - ADN du parcours de Marie"],tags:["Beaute","Creative","Social Media","Direction Artistique","Video"]},
{id:3,title:"Content Creator Social Media",company:"We Are Social",contract:"CDI",location:"Paris 10e",salary:"NC",experience:"3-5 ans",score:92,urgency:"haute",sector:"Agence Creative Internationale",url:"https://apply.workable.com/j/F6014C8525",match:["Agence creative internationale (Google, YouTube, Air France, Spotify, LEGO)","Creation quotidienne TikTok, Instagram, YouTube avec montage CapCut","Reperage de tendances et production de contenus reactifs","Teletravail flexible 2j/sem + possibilite de travailler dans 19 bureaux mondiaux","Anglais C1 requis - C2 de Marie est un vrai plus"],tags:["Agence","Social Media","TikTok","Content","International"]},
{id:4,title:"Brand Image Content Executive",company:"L'Artisan Parfumeur (Puig)",contract:"CDI",location:"Paris",salary:"NC",experience:"2-3 ans",score:91,urgency:"haute",sector:"Luxe / Parfumerie",url:"https://jobs.puig.com/job/Paris-CDI-Brand-Image-Content-Executive-L'Artisan-Parfumeur/1394423533/",match:["Direction Communication d'une maison de parfumerie de luxe (Groupe Puig)","Suivi shootings complet : preparation, production, post-production","Creation moodboards, contenus digitaux, assets social media","Accompagnement projets de la conception a la livraison finale","Maitrise Adobe + notions montage Premiere Pro - pile dans les cordes de Marie"],tags:["Luxe","Parfumerie","Brand Content","Shootings","Post-prod"]},
{id:5,title:"Videaste Social Media & Influence",company:"Havas Paris",contract:"CDI",location:"Puteaux (92)",salary:"NC",experience:"1-3 ans",score:90,urgency:"haute",sector:"Agence / Communication",url:"https://www.jobijoba.com/fr/annonce/54/48f0f2da3dbd55ded12e13eee53af8b8",match:["Havas Paris - l'une des plus grandes agences de communication","Videos pensees pour TikTok, Instagram, YouTube Shorts, LinkedIn","Tournage, montage, sound design, habillage - competences cles de Marie","Interviews de dirigeants, experts, createurs","Veille permanente tendances et proposition de formats innovants"],tags:["Agence","Video","Social Media","Influence","Tournage"]},
{id:6,title:"DA / Video Social Media",company:"Agence Gust",contract:"CDI",location:"Paris 8e",salary:"NC",experience:"5 ans+",score:88,urgency:"moyenne",sector:"Agence Digital / Social Media",url:"https://www.welcometothejungle.com/fr/companies/agencegust-com/jobs/directeur-rice-artistique-video-social-media",match:["Agence one-stop-shop : Orange, Coca-Cola, BeReal, Nivea, Vestiaire Collective","Conception a post-prod de Reels, TikTok, Stories, Shorts, motion design","Teletravail frequent + studio integre","Strategie, production et social media reunis","Vision creative forte et pilotage de la chaine de valeur complete"],tags:["Agence","Video","Social Media","Motion Design","UGC"]},
{id:7,title:"Brand & Content Manager",company:"Tandem",contract:"CDI",location:"Paris 19e",salary:"45K - 50K",experience:"4 ans+",score:85,urgency:"moyenne",sector:"Mobilite / Tech",url:"https://www.welcometothejungle.com/fr/companies/tandem/jobs/cdi-brand-content-manager_paris",match:["Strategie de contenu et deploiement editorial multi-canal","Creation contenus originaux et impactants (visuels, videos, articles)","Focus LinkedIn + B2B & B2C - double casquette comme Peech","Debut 30 septembre 2026 - poste tout frais","Salaire affiche 45-50K - transparence appreciable"],tags:["Tech","Brand Content","Social Media","Editorial","Strategie"]},
{id:8,title:"Chef de Projet International 360",company:"Dentsu Creative",contract:"CDI",location:"Paris 17e",salary:"NC",experience:"3 ans+",score:87,urgency:"moyenne",sector:"Agence / Communication Internationale",url:"https://job.jai-un-pote-dans-la.com/poste/chef-de-projet-international-h-f/",match:["Agence Dentsu Creative - campagnes deployes en France et a l'international","Suivi creation : print, digital, video, social, activation, experience","Brief production et coordination prestataires","Clients : Michelin, American Express, Ferrero, Adobe, GRDF","Teletravail indemnise + environnement tres flexible"],tags:["Agence","International","Video","360","Production"]}
];
